## preparation summary
·Algorithms

    -Sorting
    -Searching
    -

·Basic method preparation

    -Read from excel/csv
    -split strings
    -Numpy array opearation
    -Data analysis in Pandas
·Basic data structure
    
    -Array
        *bisect

    -List
        *Merge two list
        *Sorting
        *Find Max/2nd Max/Min/2nd Min
        
    
    -DataFrame
    
    -Dict
    
·time series prediction

    
    
    
    


In [342]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from pandas.plotting import lag_plot
import datetime
from statsmodels.tsa.arima_model import ARIMA
from sklearn.metrics import mean_squared_error
import warnings
warnings.filterwarnings("ignore")



# Numpy

In [75]:
# random simulation
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Three-dimensional array
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)
x2

x2 shape: (3, 4)
x2 size:  12


array([[7, 7, 1, 1],
       [3, 5, 4, 3],
       [3, 0, 4, 2]])

In [76]:
# subarray
x = np.arange(10)
x[:5]  # first five elements
x[5:]  # elements after index 5
x[::2]  # every other element
x[1:6:2]  # every other element, starting at index 1, ending at 6, every 2 element
x[::-1]  # all elements, every -1 elements, reversed


# multi-demensional subarrays
x2
x2[:2, :3]
x2[:, ::2]  # all rows, every other column
x2[::-1, ::-1] # reverse all rows and columns

grid = np.arange(1, 10).reshape((3, 3)) #reshape the array
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
# Concatenation and Splitting of arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
xy = np.concatenate([x, y])

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(np.concatenate([grid, grid],axis=1)) # concatenate along the second axis=1(row combination)

x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # split the list into array, index number is 3, 5
print(x1, x2, x3)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[1 2 3] [99 99] [3 2 1]


In [83]:
import pandas as pd
rainfall = pd.read_csv('data/Seattle2014.csv')['PRCP'].values
inches = rainfall / 254.0  # 1/10mm -> inches
inches.shape


(365,)

In [90]:
x = np.array([2, 1, 4, 3, 5])
x.sort()
print(x)

x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)# return the indices of the sorted elements
print(i)

[1 2 3 4 5]
[1 0 3 2 4]


# Pandas

In [91]:
# Series object
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [93]:
# DataFrame object
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

states = pd.DataFrame({'population': population,
                       'area': area})
# states.index
# states.columns
# DataFrame.index
# DataFrame.columns
# DataFrame.values
# DataFrame.shape


population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [128]:
# First, the loc attribute allows indexing and slicing that always references the explicit index:

display(states.loc[:"California",:"population"]) # loc looks for index name
display(states.iloc[:3,:2]) #iloc looks for Python-style index [rows, columns]

population
California    38332521

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297

In [134]:
#filling NAN
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))
data

# forward-fill
data.fillna(method='ffill')
data.fillna(method='bfill')

df = pd.DataFrame([[1,      np.nan, 2],
                   [2,      3,      5],
                   [np.nan, 4,      6]])
df.fillna(method='ffill', axis=0)

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  2.0  4.0  6

In [149]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
pd.concat([df1, df2],axis = 0)
df1.append(df2)

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [156]:
# sort list
intervals = [[0,30],[2,14],[3,6]]
intervals.sort(key = lambda x:x[1],reverse = False)
intervals

[[3, 6], [2, 14], [0, 30]]